apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api
  label: coordinates-api 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coordinates-api
  template:
    metadata:
      labels:
        app: coordinates-api
    spec:
      containers:
      - name: coordinates-api
        image: taktuk/coordinates_api:v1
        ports:
        - containerPort: 8000 
        env:
          - name: POSTGRES_HOST   
            value: postgres-0.coordinates-api-svc 
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB 
            value: coordinates_db 
          - name: POSTGRES_USER
            value: postgres 
          - name: POSTGRES_PASSWORD 
            value: postgres        
