

apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc 
  labels:
    app: coordinates-api-svc 
     
spec:
  type: ClusterIP
  clusterIP: None
  selector:
        app: coordinates-api
  ports:
  - port: 5432
    name: web
    targetPort: 8000 
    

  
        